name: Unit Test
on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: "The http URL to be tested"
        required: true
        type: string

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt -r app/requirements-dev.txt
      - name: Smoke test
        run: |
          python test/smoke/test_app.py ${{ github.event.inputs.endpoint }}
