name: Unit Test
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to be tested"
        required: true
        type: string

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt -r app/requirements-dev.txt
      - name: Unit test
        run: |
          coverage run -m unittest discover -v test/unit
      - name: Unit test coverage enforcement
        run: |
          coverage report --fail-under=80
